language: node_js

node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  global:
    - REGISTRY_USER=fjjleonrobot
    - REGISTRY_PWD=fangjunjie1998

install:
  - npm install
  - CI=false npm run build

before_script:
  - docker build --tag fjjleon/bookstore-front .
  - docker run fjjleon/bookstore-front

script:
  - docker images
  
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PWD"

deploy:
  provider: script
  script: docker push fjjleon/bookstore-front
  on:
    branch: master